### ISSUE TITLE
Loss in derived-type information in property deserialization

### ISSUE THREAD

**Issue by AArnott** [madskristensen/OptionsSample#4]
The way you deserialize options, you'll drop any data that was serialized and unique to a derived type that may have been the instance of the property value when it was serialized. For example: if the options property is a `Bag` but an instance of `class DoubleBag : Bag` was assigned to that property, the whole of `DoubleBag` would be serialized but only `Bag` would be deserialized.

https://github.com/madskristensen/OptionsSample/blob/094419514b1d0874a7358d665659afbace5fcc25/src/Options/BaseOptionModel.cs#L96

On a related note, I see you're using `JsonConvert` for serialization. Is that a requirement? Or should we perhaps define two virtual methods for serialization/deserialization so that this can be overridden by another serializer if necessary? The .NET binary formatter or xml serializer for instance could preserve information about the instance type of the properties.

**Comment by madskristensen** [comment]
No, there is no particular reason for using JSON.NET to serialize. I just got that from another implementation. I like the idea of making serialization/deserialization overridable.
